### ISSUE TITLE
Add video intro

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/roomy-website#13]
Somewhere around here..
![IMG_2480](https://github.com/user-attachments/assets/1d7c32ee-9f60-4252-a626-a91ebac4b010)

We wanna embed this video:
https://www.youtube.com/watch?v=YgYKKCmcE04

Dunno if we need a named header for it. Could be ‘Intro to Project Weird’

**Comment by hnb-ku** [comment]
I made a couple of changes and the video should now be up on the landing page like so

![localhost_5173_](https://github.com/user-attachments/assets/3081fc68-8bd4-4120-acfa-63f3fd772233)

(ignore the white stuff at the bottom, it's just an artifact of the screenshot) 

The copy (heading and paragraphs) can be edited here as plain markdown

https://github.com/muni-town/weird-website/blob/main/src/routes/components/further-reading/video.md

We can still improve the layout, This is mostly about just getting it on there first.

It should be currently live on 

https://home.weird.one/

**Comment by erlend-sh** [comment]
Perfect! 👌
