### ISSUE TITLE
Weird.one frontpage

### ISSUE THREAD

**Issue by erlend-sh** [muni-town/roomy-website#27]
We need a sparse but eye-catching landing page to greet our earliest adopters. These visitors will be preloaded with some context when they arrive on our site, so we don't _yet_ have to worry about perfectly pitching Weird under the assumption of zero prior knowledge.

The page should cover:

- Weird speed intro (header + tagline)
- Signup prompt ([biolink](https://bio.link/) url-claimer style for now?)
- Further reading (info boxes and links to dedicated explainers for Big Three)
- [Weird brand identity](https://github.com/commune-os/weird/discussions/21)

---

First draft:

# Weird

*Your home on the internet* (cybernet/hinterweb/indieweb)
[flash intermittently between the default *internet* and any of the other terms, in their own unique style.]
*Your internet passport*

[sign up]

Weird is..
- your personal space in the web; magic website creation.
- a public ID card; independent 'social sign-in' for the indie web.
- (..which together enable) a network of shared purpose

---

I'm playing around with a few different tag lines. It's easy enough to capture the essence of 'ID card' + 'social sign-in'. It's hard to also hint at the NoSP in a one-liner, but it may not be necessary, since the Weird experience doesn't *start* there.

**Comment by hnb-ku** [comment]
Thanks for the writeup!

Breaking things down for my own purposes

- [x] skeleton for the landing page
- [x] copy
- [ ] branding and Weird assets
- [ ] URL-claimer work
- [ ] initial pass on the "your own page"

**Comment by erlend-sh** [comment]
For copy: solicit anything you'd like from me, but feel free to play around with your own ideas as you see fit.

**Comment by erlend-sh** [comment]
Here’s an update on the imagined page layout. I think what I laid out in the ‘First draft’ above is gonna be the secondary section of the site. The primary (first) will go more as follows:

- - -

# Weird

***Say goodbye to the old web..***

[big mashup of mainstream services and their infamous “features” (a tweet, a fb login etc.), but we rewrite their standard copy with ‘honest advertising’.]

***Say hello, again, to the weird web..***

[mashup up all the awesome indieweb services and spaces out there (codeberg, Omnivore, Supabase, Mastodon etc.), all connecting to a Weird account + website.

- - -

Here’s a mock-up, taken at night so text isn’t super clear, but you have the same text written above, and I quite liked the lighting:

![IMG_2382](https://github.com/commune-os/weird/assets/583842/53ac43e4-7923-4788-97b9-e72fedf5e0e5)

Here’s an earlier mock-up that I did, which was superceded by the above. But it’s still a good illustration of the he kind of ‘honest advertising’ we wanna do in the first illustration.

![IMG_2374](https://github.com/commune-os/weird/assets/583842/0fe67444-c587-4bc2-a729-9b38b9a915dc)

I will provide higher definition mock-ups of the two illustrations in the following days. I can get started on this sooner rather than later if I’m provided with a mashup-board of mainstream-socials UX screens for inspiration 👀

**Comment by erlend-sh** [comment]
👇 as a Good Enough intermediary, let's just make this the new copy of weird.one, no styling needed.

# Weird

The internet [used to be fun](https://projects.kwon.nyc/internet-is-fun/); the time has come to [reweird the web!](https://webdirections.org/blog/reweirding-the-web/)

We're doing our little part by making a prosocial network based on the cornerstone of the internet: [Personal websites](https://blog.jim-nielsen.com/2022/other-peoples-websites/).

Weird is a combination of two things that go together like milk & honey:

### Magic website creation

The simplest possible way to create your own personal space on the web.

### Self-sovereign internet passport

Independent 'social sign-in' for the alt-web.

🥛🍯🥰

Weird wants to be "the Google-login button of the people's web", powered by people's websites instead of totalitarian mega-platforms.

By making (or connecting) your website with Weird you will ***soon*** be able to access and interact with the [small](https://ar.al/2020/08/07/what-is-the-small-web/), [open](https://openalternative.co/) and [indie](https://indieweb.org/) web just as easily as the regular web works today. Same conveniences, without the dark patterns, spying and data theft ✨ 

For more on why this matters, fellow internet nerds are welcome to read on:

- https://blog.erlend.sh/weird-web-pages
- https://blog.erlend.sh/weird-netizens
- https://blog.commune.sh/weird-happenings/

**Comment by erlend-sh** [comment]
## Subsection: Magic website creator

To fully inhabit the World Wide Web you need to create your digital self within it. The way to do that is with a personal website [why? Links1,2,3]

For a lot of us, the “simple” prospect of filling in that web page with content presents an insurmountable [writer’s block](https://en.wikipedia.org/wiki/Writer%27s_block). (Can we make this look like a special Wikipedia-specific link?)

That’s why we start with *link lists* as a primitive building block. Make a _list_ of 1, 3 or however many `links` that say something, anything, about you.

Whatever you’ve listed, you’ve done it! You told us something about your self, and with that you are taking up a bit of space on the web, as you should.

## Subsection: Web Passports

Weird is the “Google-login” button of the alt-web. A [web of the people](https://blog.erlend.sh/web-of-the-people), powered by people's websites instead of those pesky totalitarian mega-platforms.

By making - or merely connecting - your website with Weird you will soon be able to access and interact with the small, open and indie web just as easily as the regular web works today. Same conveniences, without the dark patterns, spying and data theft.

**Comment by erlend-sh** [comment]
Backups of our latest copy, which will be phased out soon:

### Magic Website Creator

To fully inhabit the World Wide Web you need to create your digital self within it.

For a lot of us, the “simple” prospect of filling in that web page with content presents an insurmountable [writer’s block](https://en.wikipedia.org/wiki/Writer%27s_block).

That’s why we start with link lists as a primitive building block. Make a list of 1, 3 or however many links that say something, anything, about you.

Whatever you’ve listed, you’ve done it! You told us something about your self, and with that you are taking up a bit of space on the web, as you should.

### Web Passports

Weird is the “Google-login” button of the alt-web. A [web of the people](https://blog.erlend.sh/web-of-the-people), powered by people's websites instead of those pesky totalitarian mega-platforms.

By making - or merely connecting - your website with Weird you will soon be able to access and interact with the small, open and indie web just as easily as the regular web works today. Same conveniences, without the dark patterns, spying and data theft.


- - -


Rewrite:

> That’s why we start with essentially a single text box, for you to say something, anything, about yourself. With that, you are taking up a bit of space on the web, as you should.

Web Passports should be one of several subsection in the Upcoming: Weird Network:

- web passports
- federated webrings
- network of shared purpose

**Comment by erlend-sh** [comment]
*Weird is still in the alpha stage, but 

## Your starter-pack for [property-ownership on the internet](https://den.dev/blog/be-a-property-owner-not-a-renter-on-the-internet/)

### Available today

- **Snazzy personal website:** Link to all your stuff and begin reconsolidating your fragmented online identity, [POSSE](https://indieweb.org/POSSE) style.
- **Custom domain:** Get a sub-domain on `weird.one`, or set up your own personal domain.
- Automatic Linktree importer (has to be manually requested for now)
- A social network without a content-creation imperative
- Big dreams ✨


#### Coming shortly

- Lots more importers (taking requests!)
- [Custom themes](https://github.com/muni-town/weird/issues/11)
- [Collaborative writing (CRDT)](https://github.com/muni-town/weird/issues/264)
- [Login with Bluesky (ATProto)](https://github.com/muni-town/weird/issues/206)
- [Private content](https://blog.muni.town/capabilities-and-identity-with-leaf/)
- [Teams and Projects](https://github.com/muni-town/weird/discussions/20) (👈this is where the socializing begins in earnest)
